### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by grizzly-monkey** [rohitsahu4/glabbr-task#1]
Hey Rohit ,

Thanks for the submission.
Can you make below changes ?
1) Display each plan as card with pop on hover effect eg: https://ghost.org/docs/
2) Have a button which will run a post request of  plan selected https://webhook.site/1cd8ea5a-46ac-4768-95a1-3fe8e189bbba

**Comment by rohitsahu4** [comment]
HI, I have added the changes.
